
;	prologue.h	
;	standard prologue for MSC assembly code
;	This file defines the correct ordering of segments

_TEXT	SEGMENT  BYTE PUBLIC 'CODE'
_TEXT	ENDS
_DATAB	SEGMENT  PARA PUBLIC 'DATA'
_DATAB	ENDS
_DATA	SEGMENT  BYTE PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT  BYTE PUBLIC 'CONST'
CONST	ENDS
_DATAT	SEGMENT  BYTE PUBLIC 'CONST'
_DATAT	ENDS
_BSS	SEGMENT  BYTE PUBLIC 'BSS'
_BSS	ENDS
C_COMMON SEGMENT BYTE PUBLIC 'BSS'
C_COMMON ENDS
_DATAU	SEGMENT  BYTE PUBLIC 'BSS'
_DATAU	ENDS
_DATAV	SEGMENT  BYTE PUBLIC 'BSS'
_DATAV	ENDS
  
  DGROUP	GROUP	_DATAB, _DATA, CONST, _DATAT, _BSS, C_COMMON, _DATAV
	ASSUME  CS: _TEXT, DS: DGROUP, SS: DGROUP, ES: DGROUP
